// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdlimqmwfzxrrasjmqhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkbGltcW13Znp4cnJhc2ptcWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODA4MTksImV4cCI6MjA2NjQ1NjgxOX0.3Fzo05ecBf7oSr2fAfKBK0pEyR5Bj4ZQujp8kKGZ3xE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);